version: '3'

networks:
  project-network:
    driver: bridge

volumes:
  mongodb:
services:
  scrapper:
    build: ./scrapper
    depends_on:
      - mongodb
  sentiment-analysis-process:
    build: ./sentiment-analysis-process
    ports:
      - "50051:50051"
  zookeeperr:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - project-network

  kafka_broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeperr
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper1:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - project-network
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: users
      MONGO_INITDB_ROOT_USERNAME : root
      MONGO_INITDB_ROOT_PASSWORD : root
#      MONGO_DB_USERNAME : 
#      MONGO_DB_PASSWORD : 
    volumes:
      - mongodb:/data/db
    networks:
      - project-network
    command: --bind_ip 0.0.0.0
