# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server/PredictionService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server/PredictionService.proto',
  package='PredictionService',
  syntax='proto3',
  serialized_options=b'P\001\242\002\003BLG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eserver/PredictionService.proto\x12\x11PredictionService\"\x14\n\x04Text\x12\x0c\n\x04text\x18\x01 \x01(\t\" \n\nPrediction\x12\x12\n\nprediction\x18\x01 \x01(\t2Z\n\x11PredictionService\x12\x45\n\x0bPredictText\x12\x17.PredictionService.Text\x1a\x1d.PredictionService.PredictionB\x08P\x01\xa2\x02\x03\x42LGb\x06proto3'
)




_TEXT = _descriptor.Descriptor(
  name='Text',
  full_name='PredictionService.Text',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='PredictionService.Text.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=73,
)


_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='PredictionService.Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prediction', full_name='PredictionService.Prediction.prediction', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['Text'] = _TEXT
DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'server.PredictionService_pb2'
  # @@protoc_insertion_point(class_scope:PredictionService.Text)
  })
_sym_db.RegisterMessage(Text)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTION,
  '__module__' : 'server.PredictionService_pb2'
  # @@protoc_insertion_point(class_scope:PredictionService.Prediction)
  })
_sym_db.RegisterMessage(Prediction)


DESCRIPTOR._options = None

_PREDICTIONSERVICE = _descriptor.ServiceDescriptor(
  name='PredictionService',
  full_name='PredictionService.PredictionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=199,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictText',
    full_name='PredictionService.PredictionService.PredictText',
    index=0,
    containing_service=None,
    input_type=_TEXT,
    output_type=_PREDICTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PREDICTIONSERVICE)

DESCRIPTOR.services_by_name['PredictionService'] = _PREDICTIONSERVICE

# @@protoc_insertion_point(module_scope)
